### ISSUE TITLE
mobile support

### ISSUE THREAD

**Issue by rares-lupascu** [leoasis/react-sound#30] opened 2017-06-18 20:21 UTC
Hi

I assumed this would work on mobile ... did i assume wrong?

thanks

**Comment by leoasis** [comment] 2017-06-18 22:43
Hi! What particularly is not working for you? Bear in mind the note on the readme, you need to configure soundmanager on mobile to work with multiple sounds: https://github.com/leoasis/react-sound#how-to-use

If there's anything else that doesn't work, let me know and/or send a PR fixing it!

**Comment by rares-lupascu** [comment] 2017-06-19 09:57
it is a single track i am currently playing ...

<Sound url={"./assets/audio/hi.mp3"} playStatus={this.state.playStatus} />

**Comment by leoasis** [comment] 2017-06-19 12:37
Can you provide more info? What's the error? What's the mobile browser/device you're using, what are you expecting. Can you provide a full working example that is minimal reproducing the issue?

**Comment by leoasis** [comment] 2017-12-26 15:47
Closing this since there's not enough info to know what's wrong, and this issue is already a bit dated. Feel free to reopen if you want to follow up

**Closed as completed by leoasis** 2017-12-26 15:47 UTC
