### ISSUE TITLE
Safari 11 - autoplaying sounds throwing uncaught promise error

### ISSUE THREAD

**Issue by kadhirvelm** [leoasis/react-sound#44] opened 2017-09-28 22:26 UTC
**Problem**:
I'm using react-sound to play certain sounds at certain intervals for a game I'm creating. It all works excellently on most browsers, except Safari 11. Every time I try and play a sound on that browser specifically, I get this error:

> Unhandled Rejection (NotAllowedError): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**Source**
I'm fairly confident it's because it's getting caught on the new autoplay restrictions from apple: [Auto-Play Policy Change](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/). 

**Request**
The sound isn't super vital to the game, so is there a way to just catch this error, and prevent the sound from playing instead of crashing the app? Some callback I can handle myself in the case of an error?

**Replicate Error**
Autoplaying a sound on Safari 11 using react-sound. Can make a small repo replicating this problem if need be.

**Comment by leoasis** [comment] 2017-11-07 15:13
Hi! Sorry for the late response.

This library is a thin wrapper around [Sound Manager 2](https://github.com/scottschiller/SoundManager2), and does not contain any logic besides passing the parameters to that library to play the sounds. So I'm guessing this issue is more related to that library than this one. Maybe you'd want to file an issue there?

**Comment by leoasis** [comment] 2017-12-26 15:50
Closing due to lack of follow up. Feel free to reopen if this is not a bug in soundmanager2 and is indeed a bug in this library.

**Closed as completed by leoasis** 2017-12-26 15:50 UTC

**Comment by krue-doug** [comment] 2018-08-15 15:46
I am running into the same problem except my sound is being played upon receiving web socket data. It does look like it's related to SoundManager, but I wanted to document here as well.

https://github.com/scottschiller/SoundManager2/issues/178

**Comment by krue-doug** [comment] 2018-08-15 15:54
@leoasis It looks like there is a HTML5 branch and there is a release is coming soon.

**Comment by iMerica** [comment] 2018-12-17 17:30
Issue persists on latest version of React Sound as of today.

Related: https://github.com/scottschiller/SoundManager2/issues/178

**Comment by panmona** [comment] 2019-04-16 12:03
What I don't understand yet is how the Sound component can be rendered as a reaction to a user click because this is the current browser restriction.
