### ISSUE TITLE
Not working on mobile?

### ISSUE THREAD

**Issue by hornta** [leoasis/react-sound#38] opened 2017-08-06 11:22 UTC
I have samsung s7 edge and on chrome. Works great on pc

**Comment by leoasis** [comment] 2017-08-06 22:19
What's the error you're having?

**Comment by hornta** [comment] 2017-08-07 06:16
Since I test it on mobile I am not able to an actual error or the console output. But based on my findings, I am not the only one its not working for on mobile phones.

What I see happening is that the sound is playing on desktop while its completely quiet on the phone. No, I have not muted the phone audio :-)

**Comment by leoasis** [comment] 2017-12-26 15:49
Closing this due to the lack of info. Feel free to reopen with some code to reproduce. Also, make sure it's not an issue with `soundmanager2` itself as this library is just a wrapper for it. Make sure also to read the notes in https://github.com/leoasis/react-sound#how-to-use.

**Closed as completed by leoasis** 2017-12-26 15:49 UTC

**Comment by vpontis** [comment] 2018-04-08 22:35
@leoasis I think this is related to an issue with Safari not allowing "auto-play" sounds on. 

I found this error message on MacOS High Sierra and Safari:

![image](https://user-images.githubusercontent.com/1319079/38473291-86418708-3b42-11e8-94fc-774a13a273cd.png)
